name: triggering ci

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sub-workflow
        if: github.ref == 'refs/heads/main'
        env:
          TRIGGER_TOKEN: ${{ secrets.OQS_TRIGGER_TOKEN }}
        run: |
          curl --request POST \
               --url "https://api.github.com/repos/baentsch/ghtestsub/dispatches"\
               --header "authorization: Bearer $TRIGGER_TOKEN"\
               --data "{ \"event_type\" : \"Triggered from ghtestsuper\"}"

