name: triggering ci

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
#    container:
#      image: openquantumsafe/ci-ubuntu-jammy:latest
    steps:
      - name: Just a test
        run: echo "Hello World"
      - name: Trigger sub-workflow
        env:
          TRIGGER_TOKEN: ${{ secrets.OQS_TRIGGER_TOKEN }}
# too long?               --data '{ "event_type" : "Triggered from https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}'
        run: |
          env
          echo "{ \"event_type\" : \"Triggered from $GITHUB_REPOSITORY\"}"
          curl --request POST \
               --url "https://api.github.com/repos/baentsch/ghtestsub/dispatches"\
               --header "authorization: Bearer $TRIGGER_TOKEN"\
               --data "{ \"event_type\" : \"Triggered from $GITHUB_REPOSITORY\"}"

